"""Statyczna klasyfikacja sektorowa GPW pozyskana ze strony gpw.pl/wskazniki."""

from __future__ import annotations

from typing import List, Optional, TypedDict


class SectorClassificationItem(TypedDict):
    code: str
    name: str
    parent_code: Optional[str]


GPW_SECTOR_CLASSIFICATION: List[SectorClassificationItem] = [
    {"code": "100", "name": "Finanse", "parent_code": None},
    {"code": "110", "name": "Banki", "parent_code": "100"},
    {"code": "111", "name": "banki komercyjne", "parent_code": "110"},
    {"code": "112", "name": "banki spółdzielcze", "parent_code": "110"},
    {"code": "113", "name": "banki hipoteczne", "parent_code": "110"},
    {
        "code": "114",
        "name": "banki państwowe i międzynarodowe",
        "parent_code": "110",
    },
    {"code": "119", "name": "pozostałe", "parent_code": "110"},
    {"code": "120", "name": "Ubezpieczenia", "parent_code": "100"},
    {"code": "121", "name": "firmy ubezpieczeniowe", "parent_code": "120"},
    {"code": "129", "name": "pozostałe", "parent_code": "120"},
    {"code": "130", "name": "Rynek kapitałowy", "parent_code": "100"},
    {"code": "131", "name": "giełdy i biura maklerskie", "parent_code": "130"},
    {"code": "132", "name": "zarządzanie aktywami", "parent_code": "130"},
    {"code": "139", "name": "pozostałe", "parent_code": "130"},
    {"code": "140", "name": "Nieruchomości", "parent_code": "100"},
    {"code": "141", "name": "sprzedaż nieruchomości", "parent_code": "140"},
    {"code": "142", "name": "wynajem nieruchomości", "parent_code": "140"},
    {"code": "149", "name": "pozostałe", "parent_code": "140"},
    {"code": "150", "name": "Leasing i faktoring", "parent_code": "100"},
    {"code": "160", "name": "Wierzytelności", "parent_code": "100"},
    {"code": "170", "name": "Pośrednictwo finansowe", "parent_code": "100"},
    {"code": "180", "name": "Działalność inwestycyjna", "parent_code": "100"},
    {"code": "190", "name": "Pozostałe", "parent_code": "100"},
    {"code": "200", "name": "Paliwa i energia", "parent_code": None},
    {"code": "210", "name": "Paliwa i gaz", "parent_code": "200"},
    {"code": "211", "name": "wydobycie i produkcja", "parent_code": "210"},
    {"code": "212", "name": "dystrybucja paliw i gazu", "parent_code": "210"},
    {"code": "219", "name": "pozostałe", "parent_code": "210"},
    {"code": "220", "name": "Energia", "parent_code": "200"},
    {"code": "221", "name": "energetyka", "parent_code": "220"},
    {"code": "222", "name": "energia odnawialna", "parent_code": "220"},
    {"code": "229", "name": "pozostałe", "parent_code": "220"},
    {"code": "230", "name": "Dystrybucja ciepła i wody", "parent_code": "200"},
    {"code": "290", "name": "Pozostałe", "parent_code": "200"},
    {"code": "300", "name": "Chemia i surowce", "parent_code": None},
    {"code": "310", "name": "Chemia", "parent_code": "300"},
    {"code": "311", "name": "chemia podstawowa", "parent_code": "310"},
    {"code": "312", "name": "chemia specjalistyczna", "parent_code": "310"},
    {"code": "319", "name": "pozostałe", "parent_code": "310"},
    {"code": "320", "name": "Górnictwo", "parent_code": "300"},
    {"code": "321", "name": "górnictwo węgla", "parent_code": "320"},
    {"code": "322", "name": "górnictwo metali", "parent_code": "320"},
    {"code": "329", "name": "pozostałe", "parent_code": "320"},
    {"code": "330", "name": "Hutnictwo", "parent_code": "300"},
    {"code": "331", "name": "hutnictwo żelaza i stali", "parent_code": "330"},
    {
        "code": "332",
        "name": "hutnictwo metali nieżelaznych",
        "parent_code": "330",
    },
    {"code": "339", "name": "pozostałe", "parent_code": "330"},
    {"code": "340", "name": "Surowce budowlane", "parent_code": "300"},
    {"code": "350", "name": "Guma i tworzywa sztuczne", "parent_code": "300"},
    {"code": "351", "name": "tworzywa sztuczne", "parent_code": "350"},
    {"code": "352", "name": "wyroby z gumy", "parent_code": "350"},
    {"code": "359", "name": "pozostałe", "parent_code": "350"},
    {"code": "360", "name": "Drewno i papier", "parent_code": "300"},
    {"code": "361", "name": "drewno", "parent_code": "360"},
    {"code": "362", "name": "papier i opakowania", "parent_code": "360"},
    {"code": "369", "name": "pozostałe", "parent_code": "360"},
    {"code": "370", "name": "Recykling", "parent_code": "300"},
    {"code": "390", "name": "Pozostałe", "parent_code": "300"},
    {
        "code": "400",
        "name": "Produkcja przemysłowa i budowlano-montażowa",
        "parent_code": None,
    },
    {"code": "410", "name": "Budownictwo", "parent_code": "400"},
    {"code": "411", "name": "budownictwo ogólne", "parent_code": "410"},
    {"code": "412", "name": "budownictwo przemysłowe", "parent_code": "410"},
    {"code": "413", "name": "inżynieria lądowa i wodna", "parent_code": "410"},
    {"code": "414", "name": "materiały budowlane", "parent_code": "410"},
    {
        "code": "415",
        "name": "instalacje budowlane i telekomunikacyjne",
        "parent_code": "410",
    },
    {"code": "419", "name": "pozostałe", "parent_code": "410"},
    {
        "code": "420",
        "name": "Przemysł elektromaszynowy",
        "parent_code": "400",
    },
    {"code": "421", "name": "urządzenia elektryczne", "parent_code": "420"},
    {"code": "422", "name": "urządzenia mechaniczne", "parent_code": "420"},
    {"code": "423", "name": "wyroby metalowe", "parent_code": "420"},
    {"code": "424", "name": "środki transportu", "parent_code": "420"},
    {"code": "429", "name": "pozostałe", "parent_code": "420"},
    {"code": "430", "name": "Transport i logistyka", "parent_code": "400"},
    {"code": "431", "name": "transport", "parent_code": "430"},
    {"code": "432", "name": "logistyka", "parent_code": "430"},
    {"code": "439", "name": "pozostałe", "parent_code": "430"},
    {
        "code": "440",
        "name": "Zaopatrzenie przedsiębiorstw",
        "parent_code": "400",
    },
    {"code": "441", "name": "artykuły elektryczne", "parent_code": "440"},
    {"code": "442", "name": "wyroby hutnicze", "parent_code": "440"},
    {"code": "443", "name": "chemikalia", "parent_code": "440"},
    {"code": "449", "name": "pozostałe", "parent_code": "440"},
    {"code": "450", "name": "Usługi dla przedsiębiorstw", "parent_code": "400"},
    {"code": "490", "name": "Pozostałe", "parent_code": "400"},
    {"code": "500", "name": "Dobra konsumpcyjne", "parent_code": None},
    {"code": "510", "name": "Artykuły spożywcze", "parent_code": "500"},
    {"code": "511", "name": "żywność", "parent_code": "510"},
    {"code": "512", "name": "napoje", "parent_code": "510"},
    {
        "code": "513",
        "name": "produkcja rolna i rybołówstwo",
        "parent_code": "510",
    },
    {"code": "519", "name": "pozostałe", "parent_code": "510"},
    {"code": "520", "name": "Odzież i kosmetyki", "parent_code": "500"},
    {"code": "521", "name": "odzież i obuwie", "parent_code": "520"},
    {
        "code": "522",
        "name": "kosmetyki i chemia gospodarcza",
        "parent_code": "520",
    },
    {"code": "529", "name": "pozostałe", "parent_code": "520"},
    {"code": "530", "name": "Wyposażenie domu", "parent_code": "500"},
    {"code": "531", "name": "meble i dywany", "parent_code": "530"},
    {
        "code": "532",
        "name": "sprzęt elektryczny i elektroniczny",
        "parent_code": "530",
    },
    {"code": "539", "name": "pozostałe", "parent_code": "530"},
    {"code": "540", "name": "Motoryzacja", "parent_code": "500"},
    {"code": "541", "name": "części samochodowe", "parent_code": "540"},
    {"code": "549", "name": "pozostałe", "parent_code": "540"},
    {"code": "590", "name": "Pozostałe", "parent_code": "500"},
    {"code": "600", "name": "Handel i usługi", "parent_code": None},
    {"code": "610", "name": "Handel hurtowy", "parent_code": "600"},
    {
        "code": "611",
        "name": "artykuły spożywcze i szybko zbywalne",
        "parent_code": "610",
    },
    {"code": "612", "name": "komputery i elektronika", "parent_code": "610"},
    {"code": "619", "name": "pozostałe", "parent_code": "610"},
    {"code": "620", "name": "Sieci handlowe", "parent_code": "600"},
    {
        "code": "621",
        "name": "artykuły codziennego użytku",
        "parent_code": "620",
    },
    {"code": "622", "name": "elektronika użytkowa", "parent_code": "620"},
    {"code": "629", "name": "pozostałe", "parent_code": "620"},
    {
        "code": "630",
        "name": "Rekreacja i wypoczynek",
        "parent_code": "600",
    },
    {"code": "631", "name": "hotele i restauracje", "parent_code": "630"},
    {"code": "632", "name": "biura podróży", "parent_code": "630"},
    {"code": "633", "name": "kluby sportowe", "parent_code": "630"},
    {"code": "634", "name": "sport i rekreacja", "parent_code": "630"},
    {"code": "639", "name": "pozostałe", "parent_code": "630"},
    {"code": "640", "name": "Media", "parent_code": "600"},
    {"code": "641", "name": "radio i telewizja", "parent_code": "640"},
    {"code": "642", "name": "wydawnictwa", "parent_code": "640"},
    {"code": "643", "name": "reklama i marketing", "parent_code": "640"},
    {"code": "644", "name": "portale internetowe", "parent_code": "640"},
    {"code": "649", "name": "pozostałe", "parent_code": "640"},
    {"code": "650", "name": "Gry", "parent_code": "600"},
    {"code": "660", "name": "Handel internetowy", "parent_code": "600"},
    {"code": "690", "name": "Pozostałe", "parent_code": "600"},
    {"code": "700", "name": "Ochrona zdrowia", "parent_code": None},
    {"code": "710", "name": "Szpitale i przychodnie", "parent_code": "700"},
    {
        "code": "720",
        "name": "Sprzęt i materiały medyczne",
        "parent_code": "700",
    },
    {"code": "730", "name": "Produkcja leków", "parent_code": "700"},
    {"code": "740", "name": "Dystrybucja leków", "parent_code": "700"},
    {"code": "750", "name": "Biotechnologia", "parent_code": "700"},
    {"code": "790", "name": "Pozostałe", "parent_code": "700"},
    {"code": "800", "name": "Technologie", "parent_code": None},
    {"code": "810", "name": "Telekomunikacja", "parent_code": "800"},
    {"code": "820", "name": "Informatyka", "parent_code": "800"},
    {"code": "821", "name": "oprogramowanie", "parent_code": "820"},
    {"code": "822", "name": "systemy informatyczne", "parent_code": "820"},
    {"code": "823", "name": "sprzęt informatyczny", "parent_code": "820"},
    {"code": "829", "name": "pozostałe", "parent_code": "820"},
    {"code": "830", "name": "Nowe technologie", "parent_code": "800"},
    {"code": "890", "name": "Pozostałe", "parent_code": "800"},
]
